[env:esp32_master]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_protocol = espota
upload_port = RAMS-ESP32.local
upload_flags =
    --auth=rams2024
lib_deps =
    adafruit/Adafruit NeoPixel@^1.12.0
    bblanchon/ArduinoJson@^7.0.0
build_flags =
    -I../shared
